<?php

define('FORM_PATH', __DIR__ . DIRECTORY_SEPARATOR .'..'. DIRECTORY_SEPARATOR .'app'. DIRECTORY_SEPARATOR .'form_handler'. DIRECTORY_SEPARATOR);
define('ROUTE_PATH', __DIR__ . DIRECTORY_SEPARATOR .'..'. DIRECTORY_SEPARATOR .'routes'. DIRECTORY_SEPARATOR);
define('AUTH_PATH', __DIR__ . DIRECTORY_SEPARATOR .'..'. DIRECTORY_SEPARATOR .'authentication'. DIRECTORY_SEPARATOR);


require_once __DIR__ . DIRECTORY_SEPARATOR .'router.config.php';


